"""New Migration

Revision ID: 03bc3452f63a
Revises: bac88b6898a9
Create Date: 2026-02-23 12:34:36.500450

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '03bc3452f63a'
down_revision: Union[str, Sequence[str], None] = 'bac88b6898a9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('genres',
    sa.Column('genre_uuid', sa.UUID(), nullable=False),
    sa.Column('name', sa.VARCHAR(length=255), nullable=False),
    sa.Column('description', sa.TEXT(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True, comment='Timestamp of when the record was soft-deleted'),
    sa.PrimaryKeyConstraint('genre_uuid')
    )
    op.create_index(op.f('ix_genres_name'), 'genres', ['name'], unique=True)
    op.create_table('movies',
    sa.Column('movie_uuid', sa.UUID(), nullable=False),
    sa.Column('title', sa.VARCHAR(length=255), nullable=False),
    sa.Column('description', sa.TEXT(), nullable=True),
    sa.Column('genre_uuid', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True, comment='Timestamp of when the record was soft-deleted'),
    sa.ForeignKeyConstraint(['genre_uuid'], ['genres.genre_uuid'], ),
    sa.PrimaryKeyConstraint('movie_uuid')
    )
    op.create_index(op.f('ix_movies_title'), 'movies', ['title'], unique=False)
    op.create_table('user_rate_movie',
    sa.Column('rate_uuid', sa.UUID(), nullable=False),
    sa.Column('user_uuid', sa.UUID(), nullable=False),
    sa.Column('movie_uuid', sa.UUID(), nullable=False),
    sa.Column('score', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True, comment='Timestamp of when the record was soft-deleted'),
    sa.CheckConstraint('score >= 1 AND score <= 10', name='check_rating_range'),
    sa.ForeignKeyConstraint(['movie_uuid'], ['movies.movie_uuid'], ),
    sa.ForeignKeyConstraint(['user_uuid'], ['users.user_uuid'], ),
    sa.PrimaryKeyConstraint('rate_uuid')
    )
    op.create_index(op.f('ix_user_rate_movie_movie_uuid'), 'user_rate_movie', ['movie_uuid'], unique=False)
    op.create_index(op.f('ix_user_rate_movie_user_uuid'), 'user_rate_movie', ['user_uuid'], unique=False)
    op.create_table('user_watch_movie',
    sa.Column('watch_uuid', sa.UUID(), nullable=False),
    sa.Column('user_uuid', sa.UUID(), nullable=False),
    sa.Column('movie_uuid', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True, comment='Timestamp of when the record was soft-deleted'),
    sa.ForeignKeyConstraint(['movie_uuid'], ['movies.movie_uuid'], ),
    sa.ForeignKeyConstraint(['user_uuid'], ['users.user_uuid'], ),
    sa.PrimaryKeyConstraint('watch_uuid')
    )
    op.create_index(op.f('ix_user_watch_movie_movie_uuid'), 'user_watch_movie', ['movie_uuid'], unique=False)
    op.create_index(op.f('ix_user_watch_movie_user_uuid'), 'user_watch_movie', ['user_uuid'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_user_watch_movie_user_uuid'), table_name='user_watch_movie')
    op.drop_index(op.f('ix_user_watch_movie_movie_uuid'), table_name='user_watch_movie')
    op.drop_table('user_watch_movie')
    op.drop_index(op.f('ix_user_rate_movie_user_uuid'), table_name='user_rate_movie')
    op.drop_index(op.f('ix_user_rate_movie_movie_uuid'), table_name='user_rate_movie')
    op.drop_table('user_rate_movie')
    op.drop_index(op.f('ix_movies_title'), table_name='movies')
    op.drop_table('movies')
    op.drop_index(op.f('ix_genres_name'), table_name='genres')
    op.drop_table('genres')
    # ### end Alembic commands ###
